codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%

comment:
  layout: "diff, flags, files"
  require_changes: false
  require_base: no
  require_head: yes
